# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gex.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'gex.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgex.proto\x12\x0bgex_profile\"\x9c\x03\n\x03Gex\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x14\n\x07min_dte\x18\x03 \x01(\x11H\x00\x88\x01\x01\x12\x18\n\x0bsec_min_dte\x18\x04 \x01(\x11H\x01\x88\x01\x01\x12\x0c\n\x04spot\x18\x05 \x01(\r\x12\x12\n\nzero_gamma\x18\x06 \x01(\r\x12\x15\n\rmajor_pos_vol\x18\x07 \x01(\r\x12\x14\n\x0cmajor_pos_oi\x18\x08 \x01(\r\x12\x15\n\rmajor_neg_vol\x18\t \x01(\r\x12\x14\n\x0cmajor_neg_oi\x18\n \x01(\r\x12$\n\x07strikes\x18\x0b \x03(\x0b\x32\x13.gex_profile.Strike\x12\x13\n\x0bsum_gex_vol\x18\x0c \x01(\x11\x12\x12\n\nsum_gex_oi\x18\r \x01(\x11\x12\x1b\n\x13\x64\x65lta_risk_reversal\x18\x0e \x01(\x11\x12/\n\nmax_priors\x18\x0f \x01(\x0b\x32\x16.gex_profile.MaxPriorsH\x02\x88\x01\x01\x42\n\n\x08_min_dteB\x0e\n\x0c_sec_min_dteB\r\n\x0b_max_priors\"u\n\x06Strike\x12\x14\n\x0cstrike_price\x18\x01 \x01(\r\x12\x0f\n\x07value_1\x18\x02 \x01(\x11\x12\x0f\n\x07value_2\x18\x03 \x01(\x11\x12(\n\x06priors\x18\x04 \x01(\x0b\x32\x13.gex_profile.PriorsH\x00\x88\x01\x01\x42\t\n\x07_priors\"\x18\n\x06Priors\x12\x0e\n\x06values\x18\x01 \x03(\x11\"8\n\tMaxPriors\x12+\n\x06tuples\x18\x01 \x03(\x0b\x32\x1b.gex_profile.MaxPriorsTuple\";\n\x0eMaxPriorsTuple\x12\x13\n\x0b\x66irst_value\x18\x01 \x01(\x11\x12\x14\n\x0csecond_value\x18\x02 \x01(\x11\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gex_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEX']._serialized_start=27
  _globals['_GEX']._serialized_end=439
  _globals['_STRIKE']._serialized_start=441
  _globals['_STRIKE']._serialized_end=558
  _globals['_PRIORS']._serialized_start=560
  _globals['_PRIORS']._serialized_end=584
  _globals['_MAXPRIORS']._serialized_start=586
  _globals['_MAXPRIORS']._serialized_end=642
  _globals['_MAXPRIORSTUPLE']._serialized_start=644
  _globals['_MAXPRIORSTUPLE']._serialized_end=703
# @@protoc_insertion_point(module_scope)
