# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderflow.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'orderflow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0forderflow.proto\x12\x0forderflow_proto\"\xd8\x07\n\tOrderflow\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x0c\n\x04spot\x18\x03 \x01(\r\x12\x1d\n\x15zero_major_long_gamma\x18\x04 \x01(\r\x12\x1e\n\x16zero_major_short_gamma\x18\x05 \x01(\r\x12\x1c\n\x14one_major_long_gamma\x18\x06 \x01(\r\x12\x1d\n\x15one_major_short_gamma\x18\x07 \x01(\r\x12\x1d\n\x15zero_major_call_gamma\x18\x08 \x01(\r\x12\x1c\n\x14zero_major_put_gamma\x18\t \x01(\r\x12\x1c\n\x14one_major_call_gamma\x18\n \x01(\r\x12\x1b\n\x13one_major_put_gamma\x18\x0b \x01(\r\x12\x1c\n\x14zero_convexity_ratio\x18\x0c \x01(\x11\x12\x1b\n\x13one_convexity_ratio\x18\r \x01(\x11\x12\x16\n\x0ezero_gex_ratio\x18\x0e \x01(\x11\x12\x15\n\rone_gex_ratio\x18\x0f \x01(\x11\x12\x16\n\x0ezero_net_vanna\x18\x10 \x01(\x11\x12\x15\n\rone_net_vanna\x18\x11 \x01(\x11\x12\x16\n\x0ezero_net_charm\x18\x12 \x01(\x11\x12\x15\n\rone_net_charm\x18\x13 \x01(\x11\x12\x1a\n\x12zero_agg_total_dex\x18\x14 \x01(\x11\x12\x19\n\x11one_agg_total_dex\x18\x15 \x01(\x11\x12\x19\n\x11zero_agg_call_dex\x18\x16 \x01(\x11\x12\x18\n\x10one_agg_call_dex\x18\x17 \x01(\x11\x12\x18\n\x10zero_agg_put_dex\x18\x18 \x01(\x11\x12\x17\n\x0fone_agg_put_dex\x18\x19 \x01(\x11\x12\x1a\n\x12zero_net_total_dex\x18\x1a \x01(\x11\x12\x19\n\x11one_net_total_dex\x18\x1b \x01(\x11\x12\x19\n\x11zero_net_call_dex\x18\x1c \x01(\x11\x12\x18\n\x10one_net_call_dex\x18\x1d \x01(\x11\x12\x18\n\x10zero_net_put_dex\x18\x1e \x01(\x11\x12\x17\n\x0fone_net_put_dex\x18\x1f \x01(\x11\x12\x15\n\rdex_orderflow\x18  \x01(\x11\x12\x15\n\rgex_orderflow\x18! \x01(\x11\x12\x1b\n\x13\x63onvexity_orderflow\x18\" \x01(\x11\x12\x19\n\x11one_dex_orderflow\x18# \x01(\x11\x12\x19\n\x11one_gex_orderflow\x18$ \x01(\x11\x12\x1f\n\x17one_convexity_orderflow\x18% \x01(\x11\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERFLOW']._serialized_start=37
  _globals['_ORDERFLOW']._serialized_end=1021
# @@protoc_insertion_point(module_scope)
